const REPLY_CHAT = "REPLY_CHAT"
const COUNT_CHAT = "COUNT_CHAT" 
const GET_CHAT = "GET_CHAT"
const GET_SINGLE_CHAT = "GET_SINGLE_CHAT"
const COUNT_CHAT_PAG = "COUNT_CHAT_PAG"
const COUNT_CHAT_NAV = "COUNT_CHAT_NAV"
const DELETE_CHAT = "DELETE_CHAT"
const CREATE_CHAT = "CREATE_CHAT"
const VIEW_CHAT = "VIEW_CHAT"


export {
    REPLY_CHAT , COUNT_CHAT ,GET_CHAT , COUNT_CHAT_PAG , DELETE_CHAT  , CREATE_CHAT , GET_SINGLE_CHAT , COUNT_CHAT_NAV ,VIEW_CHAT
}