const COUNT = "COUNT" 
const GET_CONTACTS = "GET_CONTACTS" 
const COUNT_NAV = "COUNT_NAV"
const DELETE = "DELETE"
const DELETE_ALL = "DELETE_ALL"
const VIEW = "VIEW"
const GET_ALl_CONTACTS = "GET_ALl_CONTACTS"
const COUNT_PAG = "COUNT_PAG"
const CREATE = "CREATE"
const VIEW_ALL = "VIEW_ALL"
const UPDATE_CONTACT = "UPDATE_CONTACT"



export {
    GET_CONTACTS , COUNT , COUNT_NAV , DELETE_ALL , DELETE , VIEW ,GET_ALl_CONTACTS ,COUNT_PAG , CREATE , VIEW_ALL , UPDATE_CONTACT
}