const LOGIN = "LOGIN"
const FORGOT = "FORGOT"
const EDITE_ADMIN = "EDITE_ADMIN"
const IMAGE = "IMAGE"
const COUNT_ADMIN = "COUNT_ADMIN" 
const GET_ADMIN = "GET_ADMIN"
const GET_SINGLE_ADMIN = "GET_SINGLE_ADMIN"
const COUNT_ADMIN_PAG = "COUNT_ADMIN_PAG"
const DELETE_ADMIN = "DELETE_ADMIN"
const SIGNUP = "SIGNUP"
const CREATE_ADMIN = "CREATE_ADMIN"


export {
    LOGIN , FORGOT , EDITE_ADMIN , IMAGE , COUNT_ADMIN ,GET_ADMIN , COUNT_ADMIN_PAG , DELETE_ADMIN , SIGNUP , CREATE_ADMIN , GET_SINGLE_ADMIN
}